resources:
  - identifier_glob: proportional
    capacity: 100
    safe_capacity: 10
    description: proportional example
    algorithm:
      kind: PROPORTIONAL_SHARE
      lease_length: 15
      refresh_interval: 5
  - identifier_glob: fair
    capacity: 1000
    safe_capacity: 10
    description: fair share example
    algorithm:
      kind: FAIR_SHARE
      lease_length: 15
      refresh_interval: 5
  - identifier_glob: "*"
    capacity: 1000
    safe_capacity: 10
    description: default
    algorithm:
      kind: FAIR_SHARE
      lease_length: 60
      refresh_interval: 15
